env:
  global:
    - LC_CTYPE=en_US.UTF-8
os: osx
language: c
matrix:
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - os: osx
  include:
    - osx_image: xcode6.4
    - osx_image: xcode7.1
    - osx_image: xcode7.2
    - osx_image: xcode7.3
    - osx_image: xcode8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - xcrun simctl list --json devicetypes
  - xcrun simctl list --json devices
  - xcodebuild -version
notifications:
  email: false
